# Generated by Django 3.2.5 on 2021-10-23 07:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashBoard',
            fields=[
                ('client_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=20)),
                ('client_email', models.CharField(max_length=30)),
                ('client_mobile', models.CharField(max_length=10)),
                ('client_address', models.CharField(max_length=50)),
                ('client_event', models.CharField(max_length=20)),
                ('client_status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='queries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=40)),
                ('query', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SuperUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=40)),
                ('upass', models.CharField(max_length=20)),
            ],
        ),
    ]
